CREATE TABLE local.dbo.ZPE_ISTPCOMP (
	Site varchar(50) NOT NULL,
	DataStatus varchar(50) NOT NULL,
	DataType varchar(50) NOT NULL,
	CreateBy varchar(50) NOT NULL,
	CreateDT datetime NOT NULL,
	LastEditBy varchar(50) NOT NULL,
	LastEditDT datetime NOT NULL,
	PART_NUMBER varchar(50) NOT NULL,
	SERIAL_NUMBER varchar(50) NOT NULL,
	FEATURE_CODE varchar(50) NULL,
	MATERIAL_CLASS varchar(50) NULL,
	CHARACTERISTIC varchar(50) NULL,
	COMPONENT_TYPE varchar(50) NULL,
	WWN varchar(50) NULL,
	CUST_SERIAL varchar(50) NULL,
	PARENT_MATNR varchar(50) NOT NULL,
	PARENT_SERNR varchar(50) NOT NULL,
	ECB_C varchar(50) NULL,
	EQUIPMENT_NO varchar(50) NULL,
	MAC_ADDR_C varchar(50) NULL,
	SERVICE_TAG_C varchar(50) NULL,
	POSITION_TYPE varchar(50) NULL,
	POSITION_NO varchar(50) NULL,
	CUST_PART varchar(50) NULL,
	CUST_ECREV varchar(50) NULL,
	VENDOR_PART varchar(50) NULL,
	POSITION_REQD varchar(50) NULL,
	REVISION varchar(50) NULL,
	CONSTRAINT PK__ZPE_ISTP__576338A793FF1650 PRIMARY KEY (DataStatus,LastEditBy,PART_NUMBER,SERIAL_NUMBER,PARENT_MATNR,PARENT_SERNR)
);
CREATE INDEX IX_LastEditDT ON local.dbo.ZPE_ISTPCOMP (LastEditDT DESC);
CREATE INDEX IX_ZPE_PARSER ON local.dbo.ZPE_ISTPCOMP (PARENT_SERNR);
CREATE INDEX IX_ZPE_SERNR ON local.dbo.ZPE_ISTPCOMP (SERIAL_NUMBER);
